[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "shorten-url"
authors = [{name = "Alexander", email = "support@shorten-url.com"}]
dynamic = ["version", "description"]
